### ISSUE TITLE
Fermisurface

### ISSUE THREAD

**Issue by setten** [abinit/abinit_issues#1]
When reporting bugs/issues, please supply the following information:

## System

see below

  * Abinit version
  * OS version and architecture
  * Fortran compiler 
  * MPI implementation (if any)
  * Extra libraries activated at compile-time (e.g. mkl, fftw3, scalapack ....)

## Summary

abinit leaves at producing the fermisurface file

## Error message  (if any)

--- !ERROR
message: |
    kpt =   0.00000000E+00  0.00000000E+00  0.00000000E+00
     with rank      171
    has no symmetric among the k-points used in the GS calculation
src_file: printbxsf.F90
src_line: 170
...

```
Error message found in `__ABI_MPIABORT__` or in other log files
```

## Steps to reproduce

single run of the input file

## Suggested solution (if any)

* If you have a suggestion on how to solve the issue, you may write it here.

 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 CPP options activated during the build:

                  CC_INTEL                 CXX_INTEL                  FC_INTEL
 
 HAVE_FC_ALLOCATABLE_DT...             HAVE_FC_ASYNC  HAVE_FC_COMMAND_ARGUMENT
 
        HAVE_FC_CONTIGUOUS           HAVE_FC_CPUTIME              HAVE_FC_EXIT
 
             HAVE_FC_FLUSH             HAVE_FC_GAMMA   HAVE_FC_IEEE_EXCEPTIONS
 
             HAVE_FC_IOMSG     HAVE_FC_ISO_C_BINDING        HAVE_FC_LONG_LINES
 
        HAVE_FC_MOVE_ALLOC           HAVE_FC_PRIVATE         HAVE_FC_PROTECTED
 
         HAVE_FC_STREAM_IO                  HAVE_FFT            HAVE_FFT_FFTW3
 
              HAVE_FFT_MPI           HAVE_FFT_SERIAL        HAVE_LIBPAW_ABINIT
 
               HAVE_LINALG         HAVE_LINALG_AXPBY        HAVE_LINALG_GEMM3M
 
  HAVE_LINALG_MKL_IMATCOPY   HAVE_LINALG_MKL_OMATADD  HAVE_LINALG_MKL_OMATCOPY
 
           HAVE_LINALG_MPI     HAVE_LINALG_SCALAPACK        HAVE_LINALG_SERIAL
 
                  HAVE_MPI                 HAVE_MPI2               HAVE_MPI_IO
 
 HAVE_MPI_TYPE_CREATE_S...                HAVE_NUMPY             HAVE_OS_LINUX
 
                HAVE_TIMER         HAVE_TIMER_ABINIT            HAVE_TIMER_MPI
 
         HAVE_TIMER_SERIAL         HAVE_TRIO_ETSF_IO          HAVE_TRIO_NETCDF
 
              USE_MACROAVE                                                      
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

 
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
 === Build Information === 
  Version       : 7.9.3
  Build target  : x86_64_linux_intel14.0
  Build date    : 20140915
 
 === Compiler Suite === 
  C compiler       : intel14.0
  C++ compiler     : intel14.0
  Fortran compiler : intel14.0
  CFLAGS           :  -g -O2 -vec-report0
  CXXFLAGS         :  -g -O2 -vec-report0
  FCFLAGS          : -O2 -g -extend-source -vec-report0 -noaltparam -nofpscomp -axAVX -xSSE4.2
  FC_LDFLAGS       :    -static-intel -static-libgcc
 
 === Optimizations === 
  Debug level        : basic
  Optimization level : standard
  Architecture       : intel_xeon
 
 === Multicore === 
  Parallel build : yes
  Parallel I/O   : yes
  openMP support : no
  GPU support    : no
 
 === Connectors / Fallbacks === 
  Connectors on : yes
  Fallbacks on  : yes
  DFT flavor    : none
  FFT flavor    : fftw3
  LINALG flavor : mkl+scalapack
  MATH flavor   : none
  TIMER flavor  : abinit
  TRIO flavor   : netcdf-fallback+etsf_io-fallback
 
 === Experimental features === 
  Bindings            : @enable_bindings@
  Exports             : no
  GW double-precision : no
 
 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 

 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 Default optimizations:
   --- None ---

 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by gmatteo** [comment]
Solved in v8.1.7
See also https://gitlab.abinit.org/gmatteo/abinit/commit/235ca8bcb67d3aef04de667f15270bbaebaeac9c

```diff
diff --git a/src/94_scfcv/outscfcv.F90 b/src/94_scfcv/outscfcv.F90
index 6bd1175..8f25b6c 100644
--- a/src/94_scfcv/outscfcv.F90
+++ b/src/94_scfcv/outscfcv.F90
@@ -235,7 +235,7 @@ subroutine outscfcv(atindx1,cg,compch_fft,compch_sph,cprj,dimcprj,dmatpawu,dtfil
 !Local variables-------------------------------
 !scalars
  integer,parameter :: master=0,cplex1=1,fform_den=52,rdwr2=2,rdwrpaw0=0
- integer :: bantot,fform,collect
+ integer :: bantot,fform,collect,timrev
  integer :: accessfil,coordn
  integer :: ii,ierr,ifft,ikpt,ispden,isppol
  integer :: me_fft,n1,n2,n3
@@ -300,8 +300,9 @@ subroutine outscfcv(atindx1,cg,compch_fft,compch_sph,cprj,dimcprj,dmatpawu,dtfil
  remove_inv=.false.
  if(dtset%nspden==4 .and. dtset%usedmft==1) remove_inv=.true. ! MG: why this?
 
+ timrev = 2; if (any(dtset%kptopt == [3, 4])) timrev= 1
  call crystal_init(dtset%amu_orig(:,1),crystal,dtset%spgroup,natom,dtset%npsp,ntypat, &
-& dtset%nsym,rprimd,dtset%typat,xred,dtset%ziontypat,dtset%znucl,1,&
+& dtset%nsym,rprimd,dtset%typat,xred,dtset%ziontypat,dtset%znucl,timrev,&
 & dtset%nspden==2.and.dtset%nsppol==1,remove_inv,hdr%title,&
 & dtset%symrel,dtset%tnons,dtset%symafm)
```
